name: Build Next.js Project

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
      # NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_SECRET: "f8WDEJxmUxin6LTWlRGatgxWwdLLXfx4+2HpZUUubAU="
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      # DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # POSTGRES_URL_NON_POOLING: ${{ secrets.DATABASE_URL }}
      POSTGRES_URL_NON_POOLING: "postgres://default:cn3MB4AswXLT@ep-mute-paper-94408801.us-east-1.postgres.vercel-storage.com:5432/verceldb"
      DATABASE_URL: "postgres://default:cn3MB4AswXLT@ep-mute-paper-94408801.us-east-1.postgres.vercel-storage.com:5432/verceldb"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the Next.js project
        run: pnpm run build

      # Add more steps if needed, such as deploying to a server or hosting service.
