name: Build and Deploy Next.js Project

on:
  push:
    branches:
      - main  # Adjust the branch name as needed  

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
      NEXTAUTH_SECRET: "f8WDEJxmUxin6LTWlRGatgxWwdLLXfx4+2HpZUUubAU="
      POSTGRES_URL_NON_POOLING: "postgres://default:cn3MB4AswXLT@ep-mute-paper-94408801.us-east-1.postgres.vercel-storage.com:5432/verceldb"
      DATABASE_URL: "postgres://default:cn3MB4AswXLT@ep-mute-paper-94408801.us-east-1.postgres.vercel-storage.com:5432/verceldb"
      NEXTAUTH_URL: "http://localhost:3000"
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the Next.js project
        run: pnpm run build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages
          folder: out
          github_token: ${{ secrets.GH_TOKEN }}
